// <auto-generated />
namespace SG_ASP_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditExamenToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditExamenToString));
        
        string IMigrationMetadata.Id
        {
            get { return "202105060242362_EditExamenToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
