// <auto-generated />
namespace SG_ASP_1.SGMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMedEnAuditoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMedEnAuditoria));
        
        string IMigrationMetadata.Id
        {
            get { return "202103190316599_AddMedEnAuditoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
